// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

StructuredBuffer<int> pawns;
RWTexture2D<float4> Result;
int width;
int height;

[numthreads(8,8,1)]
void CSMain (uint2 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    int2 Case = int2((((float)id.x) / 256) * width, (((float)id.y) / 256) * height);
    int c = (Case.x % 2 + Case.y % 2) != 1 ? 1 : 0;
    Result[id.xy] = float4(c, c, c, 1);
}
