// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

StructuredBuffer<int> pawns;
RWTexture2D<float4> Result;
int width;
int height;
int offsetWidth;
int offsetHeight;
int hoveredTileposition;
float4 BGColor;

[numthreads(8,8,1)]
void CSMain (uint2 id : SV_DispatchThreadID)
{
    int2 Case = int2((((float)id.x) / 256) * width, (((float)id.y) / 256) * height);

    Case.x += offsetWidth;
    Case.y += offsetHeight;

    Case.x += width;
    Case.x %= width; 

    Case.y += height;
    Case.y %= height; 
    
    int p = pawns[Case.y * width + Case.x];

    float cW = 256. / width;
    float cH = 256. / height;


    float X = (((float)id.x) / ((float)cW)) % 1.;
    float Y = (((float)id.y) / ((float)cH)) % 1.;
    
    float M = 0.05;

    float4 c = length(float2(X - .5, Y - .5)) < 0.4 && !(p == 0)? (p == 1 ? float4(0., 0., 0., 1.) : float4(1., 1., 1., 1.)) : X < M || X > (1. - M) || Y < M || Y > (1. - M) ? float4(.2, .2, .2, 1.) : BGColor;

    Result[id.xy] = c;
}
